export const routeModes = {
  home: {
    path: "/",
    classification: "client-only widget inside a static shell",
    config: "force-static",
    buildSymbol: "○",
    generation: "static route shell + CSR island",
    reason: "رزرو اقامتگاه در سراسر ایران با جستجو، مقایسه و مدیریت آسان سفر.",
  },
  search: {
    path: "/search",
    classification: "client-only widget inside a static shell",
    config: "force-static",
    buildSymbol: "○",
    generation: "static route shell + CSR island",
    reason: "جستجوی اقامتگاه بر اساس مقصد، تاریخ، ظرفیت و امکانات.",
  },
  house: {
    path: "/house/[uuid]",
    classification: "ISR public content",
    config: "revalidate = 300, dynamicParams = true, generateStaticParams = []",
    buildSymbol: "●",
    generation: "on-demand ISR route + CSR booking island",
    reason: "جزئیات اقامتگاه، قوانین، امکانات و مسیر رزرو.",
  },
  dashboard: {
    path: "/dashboard",
    classification: "dynamic authenticated",
    config: "force-dynamic",
    buildSymbol: "ƒ",
    generation: "dynamic route + CSR island",
    reason: "مدیریت رزروها، اقامتگاه‌ها، پیام‌ها و کیف پول.",
  },
  adminPanel: {
    path: "/admin-panel",
    classification: "dynamic authenticated",
    config: "force-dynamic",
    buildSymbol: "ƒ",
    generation: "dynamic route + CSR island",
    reason: "مدیریت کاربران، اقامتگاه‌ها، رزروها و پرداخت‌ها.",
  },
  editHouse: {
    path: "/dashboard/edit-house/[uuid]",
    classification: "dynamic authenticated",
    config: "force-dynamic",
    buildSymbol: "ƒ",
    generation: "dynamic route + CSR island",
    reason: "ویرایش اطلاعات، تصاویر، قیمت‌گذاری و تقویم اقامتگاه.",
  },
  login: {
    path: "/login",
    classification: "client-only widget inside a static shell",
    config: "force-static",
    buildSymbol: "○",
    generation: "static route shell + CSR island",
    reason: "ورود به حساب کاربری جات اینجاست.",
  },
  loginWithToken: {
    path: "/panel/login-with-token",
    classification: "dynamic public",
    config: "force-dynamic",
    buildSymbol: "ƒ",
    generation: "dynamic route + CSR island",
    reason:
      "Token-login URLs are request-sensitive and should not be treated as a cacheable public page.",
  },
  staticContent: {
    paths: ["/about", "/how-become-host", "/terms-of-service"],
    classification: "static",
    config: "force-static",
    buildSymbol: "○",
    generation: "static routes",
    reason: "اطلاعات رسمی جات اینجاست برای کاربران و میزبان‌ها.",
  },
  robots: {
    path: "/robots.txt",
    classification: "static metadata route",
    config: "static metadata",
    buildSymbol: "○",
    generation: "static metadata route",
    reason: "Robots policy is deployment-time public metadata.",
  },
  sitemap: {
    path: "/sitemap.xml",
    classification: "static metadata route",
    config: "static metadata",
    buildSymbol: "○",
    generation: "static metadata route",
    reason: "The sitemap currently contains deployment-known public routes only.",
  },
  mapIrSearchApi: {
    path: "/api/map-ir/search",
    classification: "dynamic route handler",
    config: "runtime request proxy",
    buildSymbol: "ƒ",
    generation: "dynamic route handler",
    reason:
      "The proxy forwards each POST body to Map.ir with no-store caching and a server-side API key.",
  },
  mapIrAutocompleteApi: {
    path: "/api/map-ir/autocomplete",
    classification: "dynamic route handler",
    config: "runtime request proxy",
    buildSymbol: "ƒ",
    generation: "dynamic route handler",
    reason:
      "The proxy forwards each POST body to Map.ir with no-store caching and a server-side API key.",
  },
};

export const expectedBuildRoutes = [
  { path: "/", symbol: routeModes.home.buildSymbol },
  { path: "/_not-found", symbol: "○" },
  { path: "/about", symbol: routeModes.staticContent.buildSymbol },
  { path: "/admin-panel", symbol: routeModes.adminPanel.buildSymbol },
  {
    path: "/api/map-ir/autocomplete",
    symbol: routeModes.mapIrAutocompleteApi.buildSymbol,
  },
  { path: "/api/map-ir/search", symbol: routeModes.mapIrSearchApi.buildSymbol },
  { path: "/dashboard", symbol: routeModes.dashboard.buildSymbol },
  {
    path: "/dashboard/edit-house/[uuid]",
    symbol: routeModes.editHouse.buildSymbol,
  },
  { path: "/house/[uuid]", symbol: routeModes.house.buildSymbol },
  { path: "/how-become-host", symbol: routeModes.staticContent.buildSymbol },
  { path: "/login", symbol: routeModes.login.buildSymbol },
  {
    path: "/panel/login-with-token",
    symbol: routeModes.loginWithToken.buildSymbol,
  },
  { path: "/robots.txt", symbol: routeModes.robots.buildSymbol },
  { path: "/search", symbol: routeModes.search.buildSymbol },
  { path: "/sitemap.xml", symbol: routeModes.sitemap.buildSymbol },
  { path: "/terms-of-service", symbol: routeModes.staticContent.buildSymbol },
];
